language: node_js
node_js:
  - "node"
script:
  - mkdir "$BUILD_OUT_DIR"
  - node ./index.js
after_success:
  - bash ./scripts/deploy-gh-pages.sh
env:
  global:
  - secure: "eL7MeL/3onYs1fYwyZlPcFHzg2GwD1ivz9eXClg98+9zWeZZkFSImJEOIFM/eOknTq3f7bxbx7TbJvzdHiVSNHCkDrWVLU2hW8uyMvAxaPdiKmrzaTKjZP7vdCKA0s5TpqwJXPXCScYWp3+V35XeGr5R1TbTe9Bm7k0882w7vtpSkYheX0YfShGbjcW1Ejq8yPnoAyFYE9KD0lBk5rKkpLI3LpSBgtu76jKG3iefzFGLvXgRb3LskaDPiFUIpc42b2/FmLVJ5FR2N/sbul+Qt+Yh2/DvvxYN9v/HAy4PrMG41YBn22rfXBGeld0dPyqsu8EV7ZB2C6eLlumznbocPkMv5Q8rV5GYSat1U4C/3Cs+GTGj22Oi6k2jnPD24Uym+44LH3G8bQz728PL6/V/2NyNIH2/cjDaIxciIdjf/mThiCV8Yx0FcpxZnqtYWYDQTyxPYHqGCLmBpLnKvVjbH2m4XGn/E7lcNYZbFvwlzFO4khnpJFesF51skRDeZD5lENQx8x82ewqImLxrPpbkicL5GdSTody52mySoP8wW1b/t6lVbaUMZB/Mt4bV5fzMDEwnE2rpAhJS4pZbIFoFu+Ni7h6yobopSa7YbzPFRDgpPraitqW33kUu1ZqNn11YTHIm4R0k0cRpMpWYo/FzkD+R+RrzkqTEXfMkdEkzUiQ="
  - COMMIT_AUTHOR_NAME: "travis-ci"
  - COMMIT_AUTHOR_EMAIL: "travis-ci@travis-ci.org"
  - SOURCE_BRANCH: "devel"
  - TARGET_BRANCH: "master"
  - GITHUB_REPO: "tehmantra/tehmantra.github.io"
  - BUILD_OUT_DIR: build
