# Site settings
title: Michael Wildman
email: michael@mwild.me
description: "Programmer, web developer, drummer. Auckland NZ"
baseurl: ""
url: "http://blog.mwild.me"
github_username:  tehmantra
disqus_shortname: mwild

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [ smart, tables, no_intra_emphasis ]
highlighter: pygments
permalink: /:year/:month/:day/:title.html
