# Site settings
title: Michael Wildman
email: michael@mwild.me
description: "Programmer, web developer, drummer. Auckland NZ"
baseurl: ""
url: "http://mwild.me"
github_username:  tehmantra

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
